pub mod advanced_scanner;
pub mod analysis;
pub mod ast;
pub mod cache;
pub mod chunking;
pub mod composition;
pub mod contract_type;
pub mod dataflow;
pub mod dependency_analyzer;
pub mod exploit_gen;
pub mod exploitability;
pub mod fetcher;
pub mod honeypot_filter;
pub mod ignore;
pub mod invariant_gen;
pub mod limits;
pub mod pattern_validator;
pub mod poc_stager;
pub mod regex_validator;
pub mod risk_scorer;
pub mod risk_scoring;
pub mod scanner;
pub mod semantic;
pub mod state_analysis;
pub mod taint;
pub mod template;
pub mod value_flow;
pub mod zeroday;

pub use advanced_scanner::{AdvancedReport, AdvancedScanner, CombinedVulnerability};
pub use analysis::{classify_modifiers, SymbolCollector};
pub use ast::{AstAnalyzer, ValidationResult};
pub use cache::Cache;
pub use composition::TemplateComposer;
pub use contract_type::{ContractType, ContractTypeDetector};
pub use dataflow::DataFlowAnalysis;
pub use dependency_analyzer::{AttackSurface, DependencyAnalyzer, DependencyGraph};
pub use exploit_gen::{ExploitGenerator, ExploitTemplate, VulnerabilityInfo};
pub use exploitability::{analyze_exploitability, ExploitAnalysis, ExploitConfidence};
pub use fetcher::ContractFetcher;
pub use honeypot_filter::HoneypotFilter;
pub use ignore::{load_ignore_patterns, IgnoreRule};
pub use invariant_gen::{GeneratedInvariant, InvariantCategory, InvariantGenerator};
pub use limits::{LoaderLimits, MatcherLimits};
pub use pattern_validator::PatternValidator;
pub use poc_stager::{PocCandidate, PocContext, PocPriority, PocStager};
pub use regex_validator::RegexValidator;
pub use risk_scorer::{RiskFactor, RiskLevel, RiskScore, RiskScorer, SeverityBreakdown};
pub use risk_scoring::{
    RiskAssessment, RiskConfig, RiskLevel as OldRiskLevel, RiskScorer as OldRiskScorer,
};
pub use scanner::Scanner;
pub use semantic::SemanticScanner;
pub use state_analysis::{Invariant, StateAnalyzer, StateViolation};
pub use taint::{Exploitability, TaintAnalyzer, TaintFlow, TaintSink, TaintSource};
pub use template::TemplateLoader;
pub use value_flow::{ExtractionType, ValueExtractionPath, ValueFlowAnalyzer};
pub use zeroday::ZeroDayFetcher;

#[cfg(test)]
mod tests;
