pub mod scanner;
pub mod semantic;
pub mod template;
pub mod fetcher;
pub mod cache;
pub mod chunking;
pub mod regex_validator;
pub mod zeroday;
pub mod dataflow;
pub mod composition;
pub mod risk_scoring;
pub mod risk_scorer;
pub mod dependency_analyzer;
pub mod taint;
pub mod value_flow;
pub mod state_analysis;
pub mod exploit_gen;
pub mod advanced_scanner;
pub mod pattern_validator;
pub mod invariant_gen;
pub mod poc_stager;
pub mod analysis;
pub mod exploitability;
pub mod honeypot_filter;
pub mod limits;
pub mod ignore;
pub mod ast;

pub use scanner::Scanner;
pub use semantic::SemanticScanner;
pub use template::TemplateLoader;
pub use fetcher::ContractFetcher;
pub use cache::Cache;
pub use regex_validator::RegexValidator;
pub use zeroday::ZeroDayFetcher;
pub use dataflow::DataFlowAnalysis;
pub use composition::TemplateComposer;
pub use risk_scoring::{RiskScorer as OldRiskScorer, RiskAssessment, RiskLevel as OldRiskLevel, RiskConfig};
pub use risk_scorer::{RiskScorer, RiskScore, RiskLevel, SeverityBreakdown, RiskFactor};
pub use dependency_analyzer::{DependencyAnalyzer, DependencyGraph, AttackSurface};
pub use taint::{TaintAnalyzer, TaintFlow, TaintSource, TaintSink, Exploitability};
pub use value_flow::{ValueFlowAnalyzer, ValueExtractionPath, ExtractionType};
pub use state_analysis::{StateAnalyzer, StateViolation, Invariant};
pub use exploit_gen::{ExploitGenerator, ExploitTemplate, VulnerabilityInfo};
pub use advanced_scanner::{AdvancedScanner, AdvancedReport, CombinedVulnerability};
pub use pattern_validator::PatternValidator;
pub use invariant_gen::{InvariantGenerator, GeneratedInvariant, InvariantCategory};
pub use poc_stager::{PocStager, PocCandidate, PocContext, PocPriority};
pub use analysis::{SymbolCollector, classify_modifiers};
pub use exploitability::{analyze_exploitability, ExploitAnalysis, ExploitConfidence};
pub use honeypot_filter::HoneypotFilter;
pub use limits::{MatcherLimits, LoaderLimits};
pub use ignore::{IgnoreRule, load_ignore_patterns};
pub use ast::{AstAnalyzer, ValidationResult};

#[cfg(test)]
mod tests;
